$(document).ready(function()
{
	$('body').addClass('xepo_ads');
});
$(document).on('click','.xepo_ads',function(e)
{
	$(this).removeClass('xepo_ads');
	window.open('https://go.ecotrackings.com/?token=kiLqmxlpMhRBOYlZGNvAk&url=https%3A%2F%2Flazada.co.id','_blank');
});
