$(document).ready(function()
{
	$('body').addClass('xepo_ads');
});
$(document).on('click','.xepo_ads',function(e)
{
	$(this).removeClass('xepo_ads');
	window.open('https://www.cpmprofitablenetwork.com/t1yhwp53gz?key=7ab8e6aefd158a8290166d3a18e15e96','_blank');
});
