$(document).ready(function()
{
	$('body').addClass('xepo_ads');
});
$(document).on('click','.xepo_ads',function(e)
{
	$(this).removeClass('xepo_ads');
	window.open('https://www.highperformancegate.com/t1y4907t?key=9580d8f4f2034ff79f21bfc777b3d612','_blank');
});
